# https://raw.githubusercontent.com/embedez/ez-cdn/697dbc6dc1496d27b96c57994130f43da7477300/.github/workflows/build.yml

on:
  push:
    branches:
      - main
      - master

jobs:
  build_and_push_to_registry:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    env:
      image_name: ghcr.io/${{ github.repository }}
      image_tag: latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # gh secret set GH_PERSONAL_TOKEN --app actions --body ghp_
          password: ${{ secrets.GH_PERSONAL_TOKEN }}

      - name: ASDF Parse
        uses: kota65535/github-asdf-parse-action@v1.1.0
        id: versions

      - name: Install nixpacks
        run: |
          curl -sSL https://nixpacks.com/install.sh | bash

      - name: Build with nixpacks
        run: |
          # label is important here in order for the package to show up on the github repo
          nixpacks build . --name ${{ env.image_name }} \
            --env NIXPACKS_PYTHON_VERSION="${{ steps.versions.outputs.python }}" \
            --env NIXPACKS_POETRY_VERSION="${{ steps.versions.outputs.poetry }}" \
            --label org.opencontainers.image.source=https://github.com/${{ github.repository }} \
            --tag latest \
            --start-cmd bin/cron-digest

      - name: Docker push
        run: |
          docker push ${{ env.image_name }}:latest
